// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DomainValues._17._0
{
    internal sealed partial class Vsix
    {
        public const string Id = "DomainValues.393db814-2cb9-41a7-af06-e39027d2773b";
        public const string Name = "DomainValues 2022";
        public const string Description = @"Makes synchronizing database lookup values and enumerations easier.";
        public const string Language = "en-US";
        public const string Version = "1.8";
        public const string Author = "Danny Quinn";
        public const string Tags = "SQL, Enum, Code Generation, Static Data, Domain Values";
    }
}
