// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DomainValues._15._0
{
    internal sealed partial class Vsix
    {
        public const string Id = "DomainValues.0f033348-888f-4802-9544-a308428b3000";
        public const string Name = "DomainValues 2017";
        public const string Description = @"Makes synchronizing database lookup values and enumerations easier.";
        public const string Language = "en-US";
        public const string Version = "1.8";
        public const string Author = "Danny Quinn";
        public const string Tags = "SQL, Enum, Code Generation, Static Data, Domain Values";
    }
}
