// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DomainValues._15._0
{
    internal sealed partial class Vsix
    {
        public const string Id = "DomainValues._15._0.0f033348-888f-4802-9544-a308428b3000";
        public const string Name = "DomainValues._15._0";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Danny Quinn";
        public const string Tags = "";
    }
}
