//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainValues.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainValues.Util.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; is a duplicate value..
        /// </summary>
        internal static string DuplicateValue {
            get {
                return ResourceManager.GetString("DuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file..
        /// </summary>
        internal static string EndOfFile {
            get {
                return ResourceManager.GetString("EndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already found a parameter that looks like the enum &apos;{0}&apos;..
        /// </summary>
        internal static string EnumDuplicate {
            get {
                return ResourceManager.GetString("EnumDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name provided for enumeration..
        /// </summary>
        internal static string EnumNoName {
            get {
                return ResourceManager.GetString("EnumNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; expects a parameter..
        /// </summary>
        internal static string ExpectsParam {
            get {
                return ResourceManager.GetString("ExpectsParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid text..
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key value &apos;{0}&apos; is marked as non db in the column row.  Cannot be used as a key..
        /// </summary>
        internal static string KeyMapsToNonDBColumn {
            get {
                return ResourceManager.GetString("KeyMapsToNonDBColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} named &apos;{1}&apos; already used in this file..
        /// </summary>
        internal static string NameAlreadyUsed {
            get {
                return ResourceManager.GetString("NameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not have a parameter..
        /// </summary>
        internal static string NoParams {
            get {
                return ResourceManager.GetString("NoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value &apos;{1}&apos; not found in the column row..
        /// </summary>
        internal static string NotFoundInColumns {
            get {
                return ResourceManager.GetString("NotFoundInColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null as and space as cannot be set to the same value..
        /// </summary>
        internal static string NullAsSpaceAs {
            get {
                return ResourceManager.GetString("NullAsSpaceAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count doesn&apos;t match header..
        /// </summary>
        internal static string RowCountMismatch {
            get {
                return ResourceManager.GetString("RowCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine meaning from string..
        /// </summary>
        internal static string TemplatePatternNotRecognised {
            get {
                return ResourceManager.GetString("TemplatePatternNotRecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was unexpected.  Expected &apos;{1}&apos;..
        /// </summary>
        internal static string UnexpectedKeyword {
            get {
                return ResourceManager.GetString("UnexpectedKeyword", resourceCulture);
            }
        }
    }
}
