using System.Collections.Generic;
using System.Linq;
using System.Text;
using DomainValues.Shared.Common;
using DomainValues.Shared.Model;
using DomainValues.Shared.Processing;
using NUnit.Framework;

namespace DomainValues.Test
{
    [TestFixture]
    public class SqlTests
    {
        [Test]
        public void ValidInputNoErrors()
        {
            var test = @"table dbo.test
                key id
                data 
                    | id | testcol |
                    | 1  | value   |";

            var output = GetData(test);

            var expected =
                "--------------------------------------------------------------------------------\r\n" +
                "-- <auto-generated>\r\n" +
                "--     This code was generated by a tool.\r\n" +
                "--\r\n" +
                "--     \\Test\\Test.dv\r\n" +
                "--\r\n" +
                "--     Changes to this file may cause incorrect behavior and will be lost if\r\n" +
                "--     the code is regenerated.\r\n" +
                "-- </auto-generated>\r\n" +
                "--------------------------------------------------------------------------------\r\n" +
                "\r\n"+
                "MERGE dbo.test AS TARGET\r\n" +
                "USING\r\n" +
                "(\r\n" +
                "    SELECT\r\n" +
                "        [id],\r\n" +
                "        [testcol]\r\n" +
                "    FROM\r\n" +
                "        (VALUES\r\n" +
                "            (N'1', N'value')\r\n" +
                "        ) AS col_data ([id],[testcol])\r\n" +
                ") AS SOURCE\r\n" +
                "    ON (\r\n" +
                "        TARGET.[id] = SOURCE.[id]\r\n" +
                ")\r\n" +
                "WHEN MATCHED THEN\r\n" +
                "    UPDATE SET\r\n" +
                "        TARGET.[testcol] = SOURCE.[testcol]\r\n" +
                "WHEN NOT MATCHED BY TARGET THEN\r\n" +
                "    INSERT\r\n" +
                "    (\r\n" +
                "        [id],\r\n" +
                "        [testcol]\r\n" +
                "    )\r\n" +
                "    VALUES\r\n" +
                "    (\r\n" +
                "        SOURCE.[id],\r\n" +
                "        SOURCE.[testcol]\r\n" +
                "    )\r\n" +
                "WHEN NOT MATCHED BY SOURCE THEN DELETE;\r\n\r\n";

            Assert.AreEqual(expected,output);
        }

        [Test]
        public void AllDbColumnsAreKeysDontIncludeUpdate()
        {
            var test = @"table dbo.test
                key id testcol
                data 
                    | id | testcol |
                    | 1  | value   |";

            var output = GetData(test);

            var expected =
                "--------------------------------------------------------------------------------\r\n" +
                "-- <auto-generated>\r\n" +
                "--     This code was generated by a tool.\r\n" +
                "--\r\n" +
                "--     \\Test\\Test.dv\r\n" +
                "--\r\n" +
                "--     Changes to this file may cause incorrect behavior and will be lost if\r\n" +
                "--     the code is regenerated.\r\n" +
                "-- </auto-generated>\r\n" +
                "--------------------------------------------------------------------------------\r\n" +
                "\r\n" +
                "MERGE dbo.test AS TARGET\r\n" +
                "USING\r\n" +
                "(\r\n" +
                "    SELECT\r\n" +
                "        [id],\r\n" +
                "        [testcol]\r\n" +
                "    FROM\r\n" +
                "        (VALUES\r\n" +
                "            (N'1', N'value')\r\n" +
                "        ) AS col_data ([id],[testcol])\r\n" +
                ") AS SOURCE\r\n" +
                "    ON (\r\n" +
                "        TARGET.[id] = SOURCE.[id]\r\n" +
                "    AND TARGET.[testcol] = SOURCE.[testcol]\r\n" +
                ")\r\n" +
                "WHEN NOT MATCHED BY TARGET THEN\r\n" +
                "    INSERT\r\n" +
                "    (\r\n" +
                "        [id],\r\n" +
                "        [testcol]\r\n" +
                "    )\r\n" +
                "    VALUES\r\n" +
                "    (\r\n" +
                "        SOURCE.[id],\r\n" +
                "        SOURCE.[testcol]\r\n" +
                "    )\r\n" + 
                "WHEN NOT MATCHED BY SOURCE THEN DELETE;\r\n\r\n";

            Assert.AreEqual(expected, output);
        }

        [Test]
        public void DontIncludeNonDbColumns()
        {
            var test = @"table dbo.test
                key id
                data 
                    | id | testcol | nondb* |
                    | 1  | value   | thing  |";

            var output = GetData(test);

            var expected =
                "--------------------------------------------------------------------------------\r\n" +
                "-- <auto-generated>\r\n" +
                "--     This code was generated by a tool.\r\n" +
                "--\r\n" +
                "--     \\Test\\Test.dv\r\n" +
                "--\r\n" +
                "--     Changes to this file may cause incorrect behavior and will be lost if\r\n" +
                "--     the code is regenerated.\r\n" +
                "-- </auto-generated>\r\n" +
                "--------------------------------------------------------------------------------\r\n" +
                "\r\n" +
                "MERGE dbo.test AS TARGET\r\n" +
                "USING\r\n" +
                "(\r\n" +
                "    SELECT\r\n" +
                "        [id],\r\n" +
                "        [testcol]\r\n" +
                "    FROM\r\n" +
                "        (VALUES\r\n" +
                "            (N'1', N'value')\r\n" +
                "        ) AS col_data ([id],[testcol])\r\n" +
                ") AS SOURCE\r\n" +
                "    ON (\r\n" +
                "        TARGET.[id] = SOURCE.[id]\r\n" +
                ")\r\n" +
                "WHEN MATCHED THEN\r\n" +
                "    UPDATE SET\r\n" +
                "        TARGET.[testcol] = SOURCE.[testcol]\r\n" +
                "WHEN NOT MATCHED BY TARGET THEN\r\n" +
                "    INSERT\r\n" +
                "    (\r\n" +
                "        [id],\r\n" +
                "        [testcol]\r\n" +
                "    )\r\n" +
                "    VALUES\r\n" +
                "    (\r\n" +
                "        SOURCE.[id],\r\n" +
                "        SOURCE.[testcol]\r\n" +
                "    )\r\n" +
                "WHEN NOT MATCHED BY SOURCE THEN DELETE;\r\n\r\n";

            Assert.AreEqual(expected, output);
        }

        [Test]
        public void DefaultNullSpaceOptions()
        {
            var test = @"table dbo.test
                key id
                data 
                    | id | col1 | col2   | col3  | col4 | col5  |
                    | 1  |      | $space | $null |      | data  |";

            var output = GetData(test);

            Assert.IsTrue(output.Contains("(N'1', null, N'', N'$null', null, N'data')"));
        }

        [Test]
        public void SpaceAsDefaultOption()
        {
            var test = @"
                space as default 

                table dbo.test
                key id
                data 
                    | id | col1 | col2   | col3  | col4 | col5  |
                    | 1  |      | $space | $null |      | data  |";

            var output = GetData(test);

            Assert.IsTrue(output.Contains("(N'1', N'', N'$space', null, N'', N'data')"),output);
        }

        [Test]
        public void NullAsAndSpaceAsAreCustomValues()
        {
            var test = @"
                null as $space
                space as $null 

                table dbo.test
                key id
                data 
                    | id | col1 | col2   | col3  | col4 | col5  |
                    | 1  |      | $space | $null |      | data  |";

            var output = GetData(test);

            Assert.IsTrue(output.Contains("(N'1', N'', null, N'', N'', N'data')"), output);
        }

        [Test]
        public void NullAsAndSpaceAsAreSameValue()
        {
            var test = @"
                null as test
                space as test

                table dbo.test
                key id
                data 
                    | id | col1 | col2   | col3  | col4 | col5  |
                    | 1  |      | $space | $null |      | data  |";

            var error = Scanner.GetSpans(test, true).SelectMany(a=>a.Errors).Single();

            Assert.AreEqual(Errors.NullAsSpaceAs, error.Message);
        }

        [Test]
        public void SingleQuotesAreDoubled()
        {
            var test = @"
                table dbo.test
                key id
                data 
                    | id | col1        |
                    | 1  | TestStrin'g |";

            var output = GetData(test);

            Assert.IsTrue(output.Contains("(N'1', N'TestStrin''g')"),output);
        }

        [Test]
        public void EscapedPipeIsUnescaped()
        {
            var test = @"
                table dbo.test
                key id
                data 
                    | id | col1         |
                    | 1  | TestStrin\|g |";

            var output = GetData(test);

            Assert.IsTrue(output.Contains("(N'1', N'TestStrin|g')"),output);
        }

        [Test]
        public void EscapedEscapedPipeIsNotUnescaped()
        {
            var test = @"
                table dbo.test
                key id
                data 
                    | id | col1           |
                    | 1  | TestStrin\\\|g |";

            var output = GetData(test);

            Assert.IsTrue(output.Contains(@"(N'1', N'TestStrin\|g')"), output);
        }
        private string GetData(string source)
        {
            var spans = Scanner.GetSpans(source, true);

            if (spans.Any(a => a.Errors.Any()))
                return spans.SelectMany(a => a.Errors.Select(b => b.Message)).Aggregate((a, b) => $"{a}\r\n{b}");

            var content = SpansToContent.Convert(spans);

            return content.GetSqlCode(@"\Test\Test.dv");
        }
    }
}
